#!/usr/bin/env bash
# It displays "To infinity and Beyond" indefinitely
#+ and a sleep 2 in between each iteration.
# It displays "I am invincible!!!" between each iteration.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
