#!/usr/bin/env bash
# it displays "FizzBuzz" if number is a multiple of 3 & 5.
# it displays "Fizz" if number is a multiple of 3
# it displays "Buzz" if number is a multiple of 5
# else it displays the number

for num in {1..100}
do
    if ((num % 3 == 0 && num % 5 == 0 ))
    then
	echo "FizzBuzz"
    elif (( num % 3 == 0 ))
    then
	echo "Fizz"
    elif (( num % 5 == 0 ))
    then
	echo "Buzz"
    else
	echo "$num"
    fi
done
