#!/usr/bin/env bash
# it displays "Best School" 10 times.
# it diplays "Hi" on the 9th iteration.

number=0

while [ $number -lt 10 ]
do
    if [ $number -eq 9 ]
    then
	echo "Hi"
    fi
    echo "Best School"
    (( number++ ))
done
